### ISSUE TITLE
IAE when previewing file in browser

### ISSUE THREAD

**Issue by marcelstoer** [zalando/intellij-swagger#230]
IntelliJ IDEA (latest): 2018.3.4
Plugin: v1.0.23

Triggering "Preview File In..." (via shortcut or the browser icons in the top right corner) fails with the following error:

```
java.lang.IllegalArgumentException: Argument for @NotNull parameter 'content' of com/intellij/notification/Notification.<init> must not be null
	at com.intellij.notification.Notification.$$$reportNull$$$0(Notification.java)
	at com.intellij.notification.Notification.<init>(Notification.java)
	at org.zalando.intellij.swagger.service.SwaggerFileService.notifyFailure(SwaggerFileService.java:63)
	at org.zalando.intellij.swagger.service.SwaggerFileService.convertSwaggerToHtml(SwaggerFileService.java:36)
	at org.zalando.intellij.swagger.ui.provider.SwaggerUiUrlProvider.getUrl(SwaggerUiUrlProvider.java:32)
...
```

**Comment by semonte** [comment]
Thank you for the report! New version 1.0.24 will fix the issue, it will be available once JetBrains accepts the new release.
