### ISSUE TITLE
`runReadAction()` exception is back

### ISSUE THREAD

**Issue by GaryGSC** [zalando/intellij-swagger#272]
Related to #205?

I got what WebStorm thinks is a "Fatal Error" today.

As far as I can tell, it's not actually stopping me from doing anything. So, at least for me, this is a low priority. I just figured you might be interested in the stack trace.

```java
Details: Current thread: Thread[ApplicationImpl pooled thread 35,4,Idea Thread Group] 890390571
; dispatch thread: false; isDispatchThread(): false
SystemEventQueueThread: Thread[AWT-EventQueue-0,6,Idea Thread Group] 1513904848

java.lang.Throwable: Read access is allowed from event dispatch thread or inside read-action only (see com.intellij.openapi.application.Application.runReadAction())
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:162)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertReadAccessAllowed(ApplicationImpl.java:1087)
	at com.intellij.psi.impl.source.tree.TreeElement.assertReadAccessAllowed(TreeElement.java:427)
	at com.intellij.psi.impl.source.tree.CompositeElement.textToCharArray(CompositeElement.java:255)
	at com.intellij.psi.impl.source.tree.CompositeElement.getText(CompositeElement.java:225)
	at com.intellij.extapi.psi.ASTDelegatePsiElement.getText(ASTDelegatePsiElement.java:146)
	at com.intellij.json.psi.impl.JsonPsiImplUtils.getName(JsonPsiImplUtils.java:33)
	at com.intellij.json.psi.impl.JsonPropertyImpl.getName(JsonPropertyImpl.java:32)
	at org.zalando.intellij.swagger.reference.usage.ReferenceSearch.processQuery(ReferenceSearch.java:28)
	at org.zalando.intellij.swagger.reference.usage.ReferenceSearch.processQuery(ReferenceSearch.java:16)
	at com.intellij.openapi.application.QueryExecutorBase.execute(QueryExecutorBase.java:77)
	at com.intellij.util.ExecutorsQuery.processResults(ExecutorsQuery.java:31)
	at com.intellij.util.AbstractQuery.forEach(AbstractQuery.java:66)
	at com.intellij.util.UniqueResultsQuery.process(UniqueResultsQuery.java:55)
	at com.intellij.util.UniqueResultsQuery.forEach(UniqueResultsQuery.java:45)
	at com.intellij.find.findUsages.FindUsagesHandler.processElementUsages(FindUsagesHandler.java:125)
	at com.intellij.find.findUsages.FindUsagesManager.lambda$createUsageSearcher$9(FindUsagesManager.java:367)
	at com.intellij.find.findUsages.FindUsagesManager$1.run(FindUsagesManager.java:288)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:731)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:164)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:586)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:86)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:151)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:403)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:311)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Versions:**
WebStorm 2019.1.2 (build #WS-191.7141.49, from May 7, 2019)
Swagger plugin v1.0.27

**Comment by semonte** [comment]
Thanks for the report, this action needs to be checked 👍

**Comment by vrindanayak** [comment]
I'm facing the same issue and it pops up multiple times when I'm working on my openapi.json in IntelliJ IDE
The Swagger plugin version I have is v1.0.27
Appreciate if this gets fixed and is available soon!
