### ISSUE TITLE
FileSystemAlreadyExistsException when opening yaml files

### ISSUE THREAD

**Issue by Guiarrd** [zalando/intellij-swagger#332]
Could not generate Swagger UI: java.nio.file.FileSystemAlreadyExistsException

**Comment by wetor** [comment]
I have the same problem, neither JSON nor yaml can be displayed, but I can open it through a browser
MacOS 10.15.4
GoLand 2021.3.4 / WebStorm 2021.3.3
```
Could not generate Swagger UI: java.nio.file.FileSystemAlreadyExistsException
```

**Comment by SamTheisens** [comment]
> I have the same problem, neither JSON nor yaml can be displayed, but I can open it through a browser MacOS 10.15.4 GoLand 2021.3.4 / WebStorm 2021.3.3
> 
> ```
> Could not generate Swagger UI: java.nio.file.FileSystemAlreadyExistsException
> ```

Same problem here.

```
IntelliJ IDEA 2022.1 (Ultimate Edition)
Build #IU-221.5080.210, built on April 12, 2022
Licensed to Samuel Theisens
Subscription is active until February 19, 2023.
Runtime version: 11.0.14.1+1-b2043.25 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 12.3.1
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 8
Registry:
    scala.erase.compiler.process.jdk.once=false
    ide.images.show.chessboard=true

Non-Bundled Plugins:
    org.zalando.intellij.swagger (1.1.2)
    org.jetbrains.plugins.go (221.5080.210)
    net.seesharpsoft.intellij.plugins.csv (2.18.2)
    name.kropp.intellij.makefile (221.5080.126)
    dev.meanmail.plugin.nginx-intellij-plugin (2021.3-2022.1)
    org.jetbrains.plugins.hocon (2022.1.0)
    com.crunch42.openapi (1.33)
    PlantUML integration (5.12.0)
    mobi.hsz.idea.gitignore (4.4.0)
    nb-mind-map-idea (1.5.1)
    intellij.prettierJS (221.5080.169)
    org.intellij.scala (2022.1.13)
    Pythonid (221.5080.212)

Kotlin: 221-1.6.20-release-285-IJ5080.210
```

**Comment by rovrevik** [comment]
Same prob.

> IntelliJ IDEA 2022.1 (Ultimate Edition)
> Build #IU-221.5080.210, built on April 11, 2022
> Runtime version: 11.0.14.1+1-b2043.25 x86_64
> VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
> macOS 10.15.7
> GC: G1 Young Generation, G1 Old Generation
> Memory: 5000M
> Cores: 12
> Registry:
>     debugger.watches.in.variables=false
>     ide.balloon.shadow.size=0
> 
> Non-Bundled Plugins:
>     org.zalando.intellij.swagger (1.1.2)
>     com.jetbrains.darkPurpleTheme (1.3)
>     String Manipulation (9.4.0)
>     PlantUML integration (5.12.0)
>     com.atlassian.bitbucket.references (2022.1.200)
> 
> Kotlin: 221-1.6.20-release-285-IJ5080.210

**Comment by longzu123** [comment]
Me too,the same problem.


> Could not generate Swagger UI: java.nio.file.FileSystemAlreadyExistsException

![1](https://user-images.githubusercontent.com/60382260/167759239-9d13db63-68f1-4e18-9ccc-30f6c12c3441.png)

**Comment by uriyger** [comment]
> Me too,the same problem.
> 
> > Could not generate Swagger UI: java.nio.file.FileSystemAlreadyExistsException
> 
> ![1](https://user-images.githubusercontent.com/60382260/167759239-9d13db63-68f1-4e18-9ccc-30f6c12c3441.png)

Same issue
MacOs 12.14
GoLand 2022.1.1
Plugin: 1.1.2

**Comment by 0kk1n4v4** [comment]
The same problem MacOs 12.5.1 (21G83)
IntelliJ IDEA 2021.3.2 (Ultimate Edition)
Swagger Zelando SE 1.1.2

Log:

11:19	Could not generate Swagger UI: java.nio.file.FileSystemAlreadyExistsException


<img width="676" alt="Снимок экрана 2022-09-06 в 11 25 37" src="https://user-images.githubusercontent.com/70743328/188585530-7aaa0015-8943-4233-8e3c-7d2376e19b53.png">
<img width="507" alt="Снимок экрана 2022-09-06 в 11 25 41" src="https://user-images.githubusercontent.com/70743328/188585536-e01f620c-4ec6-4024-a2fb-5c4e1664ad5e.png">

**Comment by neopaf** [comment]
Please?

**Comment by proger-coder** [comment]
![image](https://user-images.githubusercontent.com/72763951/196667136-d7d48925-8ee7-4408-90c1-d385c0bf762e.png)

![image](https://user-images.githubusercontent.com/72763951/196667034-ce2765b3-37d6-4e62-877e-15d090043729.png)

**Comment by corytheboyd-smartsheet** [comment]
Throwing in my plus one, same problem as everyone else.

**Comment by asaarilahti** [comment]
Would anyone be able to post a stack trace of the exception? It's not reproducible for me.

**Comment by cgrossde** [comment]
Here's the stack-trace:
```
2023-04-25 10:46:19,443 [  19330]   INFO - #o.z.i.s.s.SwaggerFileService - Error generating Swagger UI
java.nio.file.FileSystemAlreadyExistsException
	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystemProvider.newFileSystem(ZipFileSystemProvider.java:104)
	at java.base/java.nio.file.FileSystems.newFileSystem(FileSystems.java:339)
	at java.base/java.nio.file.FileSystems.newFileSystem(FileSystems.java:288)
	at org.zalando.intellij.swagger.file.SwaggerUiCreator.copyFromJar(SwaggerUiCreator.java:65)
	at org.zalando.intellij.swagger.file.SwaggerUiCreator.copySwaggerUiToTempDir(SwaggerUiCreator.java:51)
	at org.zalando.intellij.swagger.file.SwaggerUiCreator.createSwaggerUiFiles(SwaggerUiCreator.java:33)
	at org.zalando.intellij.swagger.service.SwaggerFileService.convertSwaggerToHtmlWithoutCache(SwaggerFileService.java:78)
	at org.zalando.intellij.swagger.service.SwaggerFileService.convertSwaggerToHtml(SwaggerFileService.java:39)
	at org.zalando.intellij.swagger.ui.provider.SwaggerUiUrlProvider.getUrl(SwaggerUiUrlProvider.java:34)
	at com.intellij.ide.browsers.WebBrowserUrlProvider.getUrls(WebBrowserUrlProvider.kt:33)
	at com.intellij.ide.browsers.impl.WebBrowserServiceImplKt.getUrls(WebBrowserServiceImpl.kt:78)
	at com.intellij.ide.browsers.impl.WebBrowserServiceImplKt.access$getUrls(WebBrowserServiceImpl.kt:1)
	at com.intellij.ide.browsers.impl.WebBrowserServiceImpl$Companion$getDebuggableUrls$1.apply(WebBrowserServiceImpl.kt:37)
	at com.intellij.ide.browsers.impl.WebBrowserServiceImpl$Companion$getDebuggableUrls$1.apply(WebBrowserServiceImpl.kt:18)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1856)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:647)
	at com.intellij.ide.browsers.impl.WebBrowserServiceImpl$Companion.getDebuggableUrls(WebBrowserServiceImpl.kt:38)
	at com.intellij.ide.browsers.impl.WebBrowserServiceImpl$Companion.getDebuggableUrl(WebBrowserServiceImpl.kt:47)
	at com.intellij.javascript.debugger.execution.JavaScriptDebugConfigurationProducer.setupConfigurationFromContext(JavaScriptDebugConfigurationProducer.kt:15)
	at com.intellij.javascript.debugger.execution.JavaScriptDebugConfigurationProducer.setupConfigurationFromContext(JavaScriptDebugConfigurationProducer.kt:11)
	at com.intellij.execution.actions.RunConfigurationProducer.createConfigurationFromContext(RunConfigurationProducer.java:100)
	at com.intellij.execution.actions.RunConfigurationProducer.findOrCreateConfigurationFromContext(RunConfigurationProducer.java:197)
	at com.intellij.execution.actions.PreferredProducerFind.doGetConfigurationsFromContext(PreferredProducerFind.java:118)
	at com.intellij.execution.actions.PreferredProducerFind.getConfigurationsFromContext(PreferredProducerFind.java:100)
	at com.intellij.execution.actions.PreferredProducerFind.createConfiguration(PreferredProducerFind.java:32)
	at com.intellij.execution.actions.ConfigurationContext.createConfiguration(ConfigurationContext.java:204)
	at com.intellij.execution.actions.ConfigurationContext.getConfiguration(ConfigurationContext.java:195)
	at com.intellij.execution.actions.BaseRunConfigurationAction.fullUpdate(BaseRunConfigurationAction.java:223)
	at com.intellij.execution.actions.BaseRunConfigurationAction.update(BaseRunConfigurationAction.java:185)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.lambda$performDumbAwareUpdate$0(ActionUtil.java:150)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareUpdate(ActionUtil.java:173)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.doUpdate(ActionUpdater.java:660)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$updateActionReal$4(ActionUpdater.java:128)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.callAction(ActionUpdater.java:173)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.callAction(ActionUpdater.java:153)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.updateActionReal(ActionUpdater.java:129)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$new$0(ActionUpdater.java:116)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.update(ActionUpdater.java:649)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.expandGroupChild(ActionUpdater.java:498)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$doExpandActionGroup$20(ActionUpdater.java:477)
	at com.intellij.util.containers.ContainerUtil.concat(ContainerUtil.java:1398)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.doExpandActionGroup(ActionUpdater.java:477)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.expandGroupChild(ActionUpdater.java:550)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$doExpandActionGroup$20(ActionUpdater.java:477)
	at com.intellij.util.containers.ContainerUtil.concat(ContainerUtil.java:1398)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.doExpandActionGroup(ActionUpdater.java:477)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.expandGroupChild(ActionUpdater.java:550)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$doExpandActionGroup$20(ActionUpdater.java:477)
	at com.intellij.util.containers.ContainerUtil.concat(ContainerUtil.java:1398)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.doExpandActionGroup(ActionUpdater.java:477)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.expandGroupChild(ActionUpdater.java:550)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$doExpandActionGroup$20(ActionUpdater.java:477)
	at com.intellij.util.containers.ContainerUtil.concat(ContainerUtil.java:1398)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.doExpandActionGroup(ActionUpdater.java:477)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.expandGroupChild(ActionUpdater.java:550)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$doExpandActionGroup$20(ActionUpdater.java:477)
	at com.intellij.util.containers.ContainerUtil.concat(ContainerUtil.java:1398)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.doExpandActionGroup(ActionUpdater.java:477)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.expandGroupChild(ActionUpdater.java:550)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$doExpandActionGroup$20(ActionUpdater.java:477)
	at com.intellij.util.containers.ContainerUtil.concat(ContainerUtil.java:1398)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.doExpandActionGroup(ActionUpdater.java:477)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.expandActionGroup(ActionUpdater.java:272)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$doExpandActionGroupAsync$12(ActionUpdater.java:340)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$doExpandActionGroupAsync$13(ActionUpdater.java:359)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1154)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$tryRunReadActionAndCancelBeforeWrite$17(ActionUpdater.java:391)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:158)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.tryRunReadActionAndCancelBeforeWrite(ActionUpdater.java:387)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$doExpandActionGroupAsync$14(ActionUpdater.java:359)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:188)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:608)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:175)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.runUnderDisposeAwareIndicator(BackgroundTaskUtil.java:365)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$doExpandActionGroupAsync$15(ActionUpdater.java:358)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:241)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:31)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:214)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:212)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:203)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)

```

**Comment by andreasevers** [comment]
Could it be that this conflicts with the bundled OpenApi Specification plugin?

**Comment by asaarilahti** [comment]
Could someone confirm this still occurs with version 1.3.0?

**Comment by aurelien-baudin** [comment]
Hello, I still have this issue with version 1.3.0

- IntelliJ IDEA 2023.2.5 (Ultimate Edition) Build #IU-232.10227.8, built on November 9, 2023
- MacBook Pro M2 on Sonoma 14.1.1

**Comment by 0kk1n4v4** [comment]
Hi, everyone.
I found fix,  for MacOS i replace folder in ~/Library/Caches/JetBrains/IntelliJIdea2022.1/openapi/npmLibraries/ by [this](https://youtrack.jetbrains.com/api/files/74-1315641?sign=MTcwOTUxMDQwMDAwMHwxMS0xfDc0LTEzMTU2NDF8T2xCMndSOExDQW9IcEQ3NFRXMWxLUUdHOUtnbzgzRjN6cF9XMnQxaEMyTQ0K&updated=1649931109875&forceDownload=true). Full instruction for other OS [here](https://youtrack.jetbrains.com/issue/IDEA-291069/Swagger-UI-Preview-only-shows-a-blank-page). Now my current IntelliJ IDEA 2021.3.2 works!
