### ISSUE TITLE
NPE in YamlTraversal

### ISSUE THREAD

**Issue by bdaroz** [zalando/intellij-swagger#60]
```
In file: LightVirtualFile: /apiv3-swagger.yaml
java.lang.NullPointerException
	at java.util.Objects.requireNonNull(Objects.java:203)
	at java.util.Optional.<init>(Optional.java:96)
	at java.util.Optional.of(Optional.java:108)
	at org.zalando.intellij.swagger.traversal.YamlTraversal.getKeyNameIfKey(YamlTraversal.java:37)
	at org.zalando.intellij.swagger.validator.field.FieldsValidator.validate(FieldsValidator.java:25)
	at org.zalando.intellij.swagger.annotator.YamlValidKeyAnnotator.annotate(YamlValidKeyAnnotator.java:26)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.a(DefaultHighlightVisitor.java:139)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.visit(DefaultHighlightVisitor.java:102)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:363)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:303)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:322)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:325)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:86)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:325)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:297)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:237)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:82)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:70)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.a(PassExecutorService.java:433)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1054)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.c(PassExecutorService.java:426)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:568)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:519)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.b(PassExecutorService.java:425)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:405)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:155)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

```
PyCharm 2016.3 EAP
Build #PY-163.7743.16, built on November 8, 2016
PyCharm EAP User
Expiration date: December 8, 2016
JRE: 1.8.0_112-release-408-b2 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
```

File causing the NPE:

https://github.com/bdaroz/the-blue-alliance/blob/18b6eec78fa3b45e14590ab7f9e37e944d7f25c2/static/apiv3-swagger.yaml

**Comment by semonte** [comment]
Thanks for the report. Unfortunately I wasn't able to reproduce this, I tested with Swagger Plugin version 0.0.20. 

What version are you using? Does the exception from just opening the file?

**Comment by bdaroz** [comment]
The plugin is 0.0.20. It doesn't seem to trigger on load, but it does trigger quite a few times (my last editing session had 6 triggers between start and clear of the error). Either way, a decision was made to refactor to a JSON model instead of YAML (for other reasons) so the problem hasn't reoccurred.

**Comment by semonte** [comment]
Ok, I will take a look at this anyway.

**Comment by rupert-madden-abbott** [comment]
I've got the same error with 0.0.21 which is the latest version that installs in IntelliJ. The stack trace is the same, however.

It happens very intermittently. I would assume it is probably a race condition on [this line](https://github.com/zalando/intellij-swagger/blob/master/src/main/java/org/zalando/intellij/swagger/traversal/YamlTraversal.java#L37). I'm guessing that isPresent returns true but the key text has been deleted by the time getKeyText is called.

**Comment by semonte** [comment]
Hmm, it seems we need to replace `Optional.of` to `Optional.ofNullable`. @rupert654 care to contribute :) ?

**Comment by rupert-madden-abbott** [comment]
I thought that initially too, but then I felt like I may have misunderstood what the line is doing. Let me take another look.

**Comment by semonte** [comment]
Ok great! If you have any questions I'm happy to answer.

**Comment by rupert-madden-abbott** [comment]
I'm not very familiar with this functional style since I'm normally stuck on Java 5/6 but I believe that should fix the problem whilst maintaining the intended behaviour of the method.
