### ISSUE TITLE
IllegalArgumentException in JsonTraversal

### ISSUE THREAD

**Issue by ghost** [zalando/intellij-swagger#62]
```
In file: LightVirtualFile: /swagger.json: Argument for @NotNull parameter 'element' of com/intellij/json/psi/JsonPsiUtil.isPropertyKey must not be null
java.lang.IllegalArgumentException: Argument for @NotNull parameter 'element' of com/intellij/json/psi/JsonPsiUtil.isPropertyKey must not be null
	at com.intellij.json.psi.JsonPsiUtil.isPropertyKey(JsonPsiUtil.java)
	at org.zalando.intellij.swagger.traversal.JsonTraversal.isKey(JsonTraversal.java:35)
	at org.zalando.intellij.swagger.traversal.JsonTraversal.getKeyNameIfKey(JsonTraversal.java:40)
	at org.zalando.intellij.swagger.validator.field.FieldsValidator.validate(FieldsValidator.java:25)
	at org.zalando.intellij.swagger.annotator.JsonValidKeyAnnotator.annotate(JsonValidKeyAnnotator.java:25)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.a(DefaultHighlightVisitor.java:139)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.visit(DefaultHighlightVisitor.java:102)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:363)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:303)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:322)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:325)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:86)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:325)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:297)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:237)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:82)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:70)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.b(PassExecutorService.java:433)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1054)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.a(PassExecutorService.java:426)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:568)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:519)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.c(PassExecutorService.java:425)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:405)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:155)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)


java.lang.IllegalArgumentException: Argument for @NotNull parameter 'element' of com/intellij/json/psi/JsonPsiUtil.isPropertyKey must not be null
	at com.intellij.json.psi.JsonPsiUtil.isPropertyKey(JsonPsiUtil.java)
	at org.zalando.intellij.swagger.traversal.JsonTraversal.isKey(JsonTraversal.java:35)
	at org.zalando.intellij.swagger.traversal.JsonTraversal.getKeyNameIfKey(JsonTraversal.java:40)
	at org.zalando.intellij.swagger.validator.field.FieldsValidator.validate(FieldsValidator.java:25)
	at org.zalando.intellij.swagger.annotator.JsonValidKeyAnnotator.annotate(JsonValidKeyAnnotator.java:25)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.a(DefaultHighlightVisitor.java:139)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.visit(DefaultHighlightVisitor.java:102)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:363)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:303)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:322)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:325)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:86)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:325)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:297)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:237)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:82)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:70)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.b(PassExecutorService.java:433)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1054)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.a(PassExecutorService.java:426)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:568)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:519)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.c(PassExecutorService.java:425)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:405)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:155)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

I use IDEA 2016.3 and swagger plugin v0.0.21.

**Comment by semonte** [comment]
Thanks for your report. Are you able to share the `swagger.json` file that causes the exception?

**Comment by ghost** [comment]
I'm afraid not, but I could provide altered/obfuscated version. Is it only structure and types that need to be preserved? In other words, if I change paths and various names and values, would it still be useful to you?

**Comment by semonte** [comment]
If you are able to reproduce the error with the obfuscated version it is useful.

**Comment by ghost** [comment]
I'll see what I can do to help, but it might take some time.

**Comment by rupert-madden-abbott** [comment]
I'll push a fix up for this shortly as it is a very similar issue to #60.

I should probably note that the way in which a PsiElement is determined to be a key is slightly different between YamlTraversal and JsonTraversal. In YamlTraversal, getParent is only called once. In JsonTraversal, it is called twice, once on the element passed to the method, and then again on that parent inside JsonPsiUtil::isPropertyKey.

I'm unsure if this is an error or just necessary due to the differences between YAML and JSON but thought I would point it out, just in case.
