### ISSUE TITLE
Unexpected end-of-input when binding data into ObjectNode

### ISSUE THREAD

**Issue by jakubczaplicki** [zalando/intellij-swagger#86]
Installed the plugin on PyCharm 2017.1.1.  I opened a JSON and a YAML files, and went for a lunch, leaving the laptop on for some time. When I came back I had an error popup in pycharm saying:

```
 Unexpected end-of-input when binding data into ObjectNode
 at [Source: java.io.StringReader@50f50495; line: 1389, column: 20]
com.fasterxml.jackson.databind.JsonMappingException: Unexpected end-of-input when binding data into ObjectNode
 at [Source: java.io.StringReader@50f50495; line: 1389, column: 20]
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:255)
	at com.fasterxml.jackson.databind.DeserializationContext.mappingException(DeserializationContext.java:982)
	at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeObject(JsonNodeDeserializer.java:223)
	at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeObject(JsonNodeDeserializer.java:227)
	at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeObject(JsonNodeDeserializer.java:227)
	at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeObject(JsonNodeDeserializer.java:227)
	at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeObject(JsonNodeDeserializer.java:227)
	at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeObject(JsonNodeDeserializer.java:227)
	at com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer.deserialize(JsonNodeDeserializer.java:69)
	at com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer.deserialize(JsonNodeDeserializer.java:15)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3807)
	at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:2332)
	at org.zalando.intellij.swagger.ui.SwaggerUiUrlProvider.jsonToYaml(SwaggerUiUrlProvider.java:62)
	at org.zalando.intellij.swagger.ui.SwaggerUiUrlProvider.getSpecificationContentAsJson(SwaggerUiUrlProvider.java:56)
	at org.zalando.intellij.swagger.ui.SwaggerUiUrlProvider.getUrl(SwaggerUiUrlProvider.java:47)
	at com.intellij.ide.browsers.WebBrowserUrlProvider.getUrls(WebBrowserUrlProvider.kt:54)
	at com.intellij.ide.browsers.impl.WebBrowserServiceImplKt.a(WebBrowserServiceImpl.kt:92)
	at com.intellij.ide.browsers.impl.WebBrowserServiceImplKt.access$getUrls(WebBrowserServiceImpl.kt:1)
	at com.intellij.ide.browsers.impl.WebBrowserServiceImpl$Companion.getDebuggableUrls(WebBrowserServiceImpl.kt:52)
	at com.intellij.ide.browsers.impl.WebBrowserServiceImpl$Companion.getDebuggableUrl(WebBrowserServiceImpl.kt:61)
	at com.intellij.javascript.debugger.execution.JavaScriptDebugConfigurationProducer.setupConfigurationFromContext(JavaScriptDebugConfigurationProducer.kt:13)
	at com.intellij.javascript.debugger.execution.JavaScriptDebugConfigurationProducer.setupConfigurationFromContext(JavaScriptDebugConfigurationProducer.kt:11)
	at com.intellij.execution.actions.RunConfigurationProducer.createConfigurationFromContext(RunConfigurationProducer.java:90)
	at com.intellij.execution.actions.RunConfigurationProducer.findOrCreateConfigurationFromContext(RunConfigurationProducer.java:178)
	at com.intellij.execution.actions.PreferredProducerFind.getConfigurationsFromContext(PreferredProducerFind.java:107)
	at com.intellij.execution.actions.PreferredProducerFind.findConfigurationFromContext(PreferredProducerFind.java:132)
	at com.intellij.execution.actions.PreferredProducerFind.createConfiguration(PreferredProducerFind.java:43)
	at com.intellij.execution.actions.ConfigurationContext.createConfiguration(ConfigurationContext.java:148)
	at com.intellij.execution.actions.ConfigurationContext.getConfiguration(ConfigurationContext.java:139)
	at com.intellij.execution.actions.BaseRunConfigurationAction.update(BaseRunConfigurationAction.java:187)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareUpdate(ActionUtil.java:131)
	at com.intellij.openapi.actionSystem.impl.Utils.a(Utils.java:234)
	at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroup(Utils.java:179)
	at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroup(Utils.java:204)
	at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroup(Utils.java:204)
	at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroup(Utils.java:204)
	at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroup(Utils.java:204)
	at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroup(Utils.java:99)
	at com.intellij.openapi.actionSystem.impl.Utils.fillMenu(Utils.java:340)
	at com.intellij.openapi.actionSystem.impl.ActionPopupMenuImpl$MyMenu.show(ActionPopupMenuImpl.java:98)
	at com.intellij.ide.ui.customization.CustomizationUtil$2.invokePopup(CustomizationUtil.java:290)
	at com.intellij.ui.PopupHandler.mousePressed(PopupHandler.java:48)
	at java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:280)
	at java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:279)
	at java.awt.Component.processMouseEvent(Component.java:6538)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at com.intellij.ui.treeStructure.Tree.processMouseEvent(Tree.java:410)
	at com.intellij.ide.dnd.aware.DnDAwareTree.processMouseEvent(DnDAwareTree.java:58)
	at java.awt.Component.processEvent(Component.java:6306)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4897)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4719)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4522)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4719)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:737)
	at java.awt.EventQueue$4.run(EventQueue.java:735)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at com.intellij.ide.IdeEventQueue.b(IdeEventQueue.java:827)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:651)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:365)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by semonte** [comment]
Thanks for reporting the issue. We need to catch all parsing exceptions, the plugin currently expects the JSON to be valid.
